---
version: "3"
services:
        nginx:
                image: fholzer/nginx-brotli:latest
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf:ro
                links:
                        - authldap
                ports:
                        - "0.0.0.0:80:80"
        authldap:
                image: fholzer/nginx-auth-subrequest-ldap:latest
                volumes:
                        - ./config.ini:/etc/ldap/nginx_ldap_bind.ini:ro
